import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/Header";
import Ilustration from "../../public/images/page-illustration.svg";
import BlurredShapeGray from "../../public/images/blurred-shape-gray.svg";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const nacelle = localFont({
  src: [
    {
      path: "../../public/fonts/nacelle-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/nacelle-italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/nacelle-semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/nacelle-semibolditalic.woff2",
      weight: "600",
      style: "italic",
    },
  ],
  variable: "--font-nacelle",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${nacelle.variable} flex flex-col items-center bg-gray-950 antialiased`}>
        <div className="relative max-w-6xl w-full min-h-screen shrink-0">
          <div className="absolute -top-10 left-60 z-0">
            <BlurredShapeGray className="w-full h-full" />
          </div>
          <div className="absolute top-0 -right-16 z-0">
            <Ilustration className="w-full h-full" />
          </div>
          <div className="relative z-10">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
