"use client";

import React, { useState } from "react";
import ButtonIcon01 from "../../../../public/images/button-icon-01.svg";
import ButtonIcon02 from "../../../../public/images/button-icon-02.svg";
import ButtonIcon03 from "../../../../public/images/button-icon-03.svg";
import ButtonIcon04 from "../../../../public/images/button-icon-04.svg";
import ButtonIcon05 from "../../../../public/images/button-icon-05.svg";

import TestimonialImg01 from "../../../../public/images/testimonial-01.jpg";
import TestimonialImg02 from "../../../../public/images/testimonial-02.jpg";
import TestimonialImg03 from "../../../../public/images/testimonial-03.jpg";
import TestimonialImg04 from "../../../../public/images/testimonial-04.jpg";
import TestimonialImg05 from "../../../../public/images/testimonial-05.jpg";
import TestimonialImg06 from "../../../../public/images/testimonial-06.jpg";
import TestimonialImg07 from "../../../../public/images/testimonial-07.jpg";
import TestimonialImg08 from "../../../../public/images/testimonial-08.jpg";
import TestimonialImg09 from "../../../../public/images/testimonial-09.jpg";
import ClientImg01 from "../../../../public/images/client-logo-01.svg";
import ClientImg02 from "../../../../public/images/client-logo-02.svg";
import ClientImg03 from "../../../../public/images/client-logo-03.svg";
import ClientImg04 from "../../../../public/images/client-logo-04.svg";
import ClientImg05 from "../../../../public/images/client-logo-05.svg";
import ClientImg06 from "../../../../public/images/client-logo-06.svg";
import ClientImg07 from "../../../../public/images/client-logo-07.svg";
import ClientImg08 from "../../../../public/images/client-logo-08.svg";
import ClientImg09 from "../../../../public/images/client-logo-09.svg";
import Image from "next/image";
import useMasonry from "@/hooks/useMasonry";

const testimonials = [
  {
    img: TestimonialImg01,
    clientImg: ClientImg01,
    name: "MaKayla P.",
    company: "Disney",
    content:
      "As a content creator, I was always on the lookout for a tool that could help me keep up with the demand. The AI-driven content tool has been a game-changer. It generates high-quality content in a fraction of the time it used to take me.",
    categories: [1, 3, 5],
  },
  {
    img: TestimonialImg02,
    clientImg: ClientImg02,
    name: "Andrew K.",
    company: "Samsung",
    content:
      "I've tried several content generation tools, but this AI-driven tool is by far the best. It understands my brand's voice and consistently produces content that resonates with my audience!",
    categories: [1, 2, 4],
  },
  {
    img: TestimonialImg03,
    clientImg: ClientImg03,
    name: "Lucy D.",
    company: "Rio",
    content:
      "Content creation used to be a bottleneck in our workflow, but not anymore. This AI tool is intuitive and produces top-notch content every time. It's like having an extra team member who never sleeps! Definitely recommend.",
    categories: [1, 2, 5],
  },
  {
    img: TestimonialImg04,
    clientImg: ClientImg04,
    name: "Pavel M.",
    company: "Canon",
    content:
      "The quality of the content generated by this AI tool is outstanding. It has taken our content marketing to new heights, allowing us to publish more frequently without compromising on quality. Highly recommended for anyone.",
    categories: [1, 4],
  },
  {
    img: TestimonialImg05,
    clientImg: ClientImg05,
    name: "Miriam E.",
    company: "Cadbury",
    content:
      "The AI-driven content tool has been a lifesaver for my marketing agency. We can now produce high-quality content for multiple clients quickly and efficiently. It's an invaluable asset to our team.",
    categories: [1, 3, 5],
  },
  {
    img: TestimonialImg06,
    clientImg: ClientImg06,
    name: "Eloise V.",
    company: "Maffell",
    content:
      "I'm amazed at how well this AI-driven content tool performs. It's incredibly versatile and can generate content for blogs, social media, and even product descriptions effortlessly. It's fantastic!",
    categories: [1, 3],
  },
  {
    img: TestimonialImg07,
    clientImg: ClientImg07,
    name: "Pierre-Gilles L.",
    company: "Binance",
    content:
      "I was blown away by how easy it was to create my content using this tool! Within a few hours, I had a professional-looking platform up and running, and my client could not believe it.",
    categories: [1, 2, 5],
  },
  {
    img: TestimonialImg08,
    clientImg: ClientImg08,
    name: "Danielle K.",
    company: "Forbes Inc.",
    content:
      "I've never been a fan of complicated website AI tools, which is why Open PRO is perfect for me. Its minimalist design and simple functionality make staying organized feel like second nature.",
    categories: [1, 4],
  },
  {
    img: TestimonialImg09,
    clientImg: ClientImg09,
    name: "Mary P.",
    company: "Ray Ban",
    content:
      "I've never been one for coding, so finding an AI tool that doesn't require any technical skills was a dream come true. This tool exceeded my expectations, and I'm proud to show off my new stuff to friends.",
    categories: [1, 2],
  },
];

export default function Testimonials() {
  const masonryContainer = useMasonry();
  const [category, setCatgeory] = useState<number>(1);

  const buttons = [
    {
      Icon: ButtonIcon01,
      text: "View All",
      category: 1,
    },
    {
      Icon: ButtonIcon02,
      text: "Software",
      category: 2,
    },
    {
      Icon: ButtonIcon03,
      text: "Financial",
      category: 3,
    },
    {
      Icon: ButtonIcon04,
      text: "eCommerce",
      category: 4,
    },
    {
      Icon: ButtonIcon05,
      text: "Education",
      category: 5,
    },
  ];

  return (
    <div className="mb-20">
      <div className="mb-3">
        <div className="flex items-center justify-center gap-[10px]">
          <div className="w-8 h-[1px] bg-linear-to-r from-0% from-[#C7D2FE]/[0%] to-100% to-[#C7D2FE]/[48%]"></div>
          <div>
            <p className="animate-gradient bg-linear-to-r from-0% from-[#6366F1] to-100% to-[#C7D2FE] bg-clip-text text-transparent">
              Worth Tracking
            </p>
          </div>
          <div className="w-8 h-[1px] bg-linear-to-l from-0% from-[#C7D2FE]/[0%] to-100% to-[#C7D2FE]/[48%]"></div>
        </div>
      </div>

      <div className="flex flex-col items-center justify-center mb-12">
        <h2 className="animate-gradient bg-[linear-gradient(to_right,_#F9FAFB,_#E5E7EB,_#C7D2FE,_#E5E7EB,_#F9FAFB)] bg-[length:200%_auto] bg-clip-text font-nacelle font-semibold text-transparent text-[40px] mb-4">
          Don{"'"}t take our word for it
        </h2>
        <p className="text-lg leading-7 text-center tracking-[-0.25px] text-[#838AA7]">
          We provide tech-first solutions that empower decision-makers to build healthier and happier <br /> workspaces
          from anywhere in the world.
        </p>
      </div>

      <div className="flex justify-center mb-16">
        <div className="w-fit rounded-3xl bg-[#1F2937]/40 p-1 inline-flex flex-wrap">
          {/* buttons */}
          {buttons.map((item, index) => (
            <button
              key={index}
              className={`cursor-pointer transition-opacity ${
                category === item.category ? "opacity-100" : "opacity-65"
              }`}
              onClick={() => setCatgeory(item.category)}
            >
              <div
                className={`rounded-2xl p-px transition-colors ${
                  category === item.category
                    ? "bg-linear-to-b from-0% from-[#6366F1]/0 via-50% via-[#6366F1]/0 to-100% to-[#6366F1]/50" /* stroke */
                    : ""
                }`}
              >
                <div
                  className={`rounded-[calc(1rem-1px)] transition-colors ${
                    category === item.category
                      ? "bg-linear-to-b from-0% from-[#111827] via-55% via-[#1F2937]/[48%] to-100% to-[#111827]" /* background */
                      : ""
                  }`}
                >
                  <div className="flex items-center justify-center gap-2 px-3 py-1">
                    <div className={`${category === item.category ? "text-[#6366F1]" : "text-[#4B5563]"}`}>
                      <item.Icon />
                    </div>
                    <p className="text-sm text-[#E5E7EB]">{item.text}</p>
                  </div>
                </div>
              </div>
            </button>
          ))}
        </div>
      </div>

      <div className="grid items-start grid-cols-3 gap-6" ref={masonryContainer}>
        {testimonials.map((item, index) => (
          <div
            key={index}
            className={`transition-opacity ${item.categories.includes(category) ? "opacity-100" : "opacity-30"}`}
          >
            <div className="rounded-2xl bg-linear-to-r p-px from-0% from-[#1F2937]/80 via-50% via-[#374151] to-100% to-[#1F2937]/80">
              <div className="rounded-[calc(1rem-1px)] bg-[#111827] px-5 py-6 flex flex-col gap-4">
                <div>
                  <item.clientImg />
                </div>
                <p className="text-sm tracking-[-0.25px] text-[#838AA7] before:content-['“'] after:content-['”']">
                  {item.content}
                </p>
                <div className="flex items-center gap-2">
                  <Image
                    src={item.img}
                    alt=""
                    width={0}
                    height={0}
                    sizes="100vw"
                    className="w-9 h-9 rounded-full object-cover object-center"
                  />
                  <div>
                    <p className="font-medium text-sm tracking-[-0.25px] text-[#E5E7EB]">
                      {item.name} <span className="text-[#374151]">-</span>{" "}
                      <span className="cursor-pointer text-[#838AA7] transition-colors hover:text-[#6366F1]">
                        {item.company}
                      </span>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
